### ISSUE TITLE
BUG: Does not display STATS 

### ISSUE THREAD

**Issue by ChintzRuparel** [Ashutosh00710/github-readme-activity-graph#173] opened 2022-12-06 14:45 UTC
**Describe the bug**
Does not display STATS 

**To Reproduce**
Check my Profile out!
On the readme activity stats are not displayed 

**Expected behavior**
Activity Bar Graph Display 

**Screenshots**
<img width="600" alt="Screenshot 2022-12-06 at 20 08 03" src="https://user-images.githubusercontent.com/51440734/205942623-4b850d6e-c888-45d5-b432-72ff47b1b332.png">

**Desktop (please complete the following information):**
 - OS: macOS Ventura 
 - Browser Google Chrome
 - Version : NaN

**Smartphone (please complete the following information):**
 ~null~

**Additional context**
Please send a detailed guide to solve this as this makes a very important part of GitHub Stats

**Comment by Kshitij978** [comment] 2022-12-06 15:16
Duplicate of #169

**Closed** 2022-12-06 15:19 UTC
Labels: bug
